openapi: 3.0.1
info:
  title: monster-ki-rin
  x-cortex-tag: monster-ki-rin
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: celestial
    challenge_rating: 12
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-ki-rin
      alias: github-token-test
